version: 2
jobs:
  build:
    working_directory: ~/doczy
    docker:
      - image: circleci/node:8.0.0
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Install dependencies
        command: yarn install
    - run:
        name: Run tests
        command: yarn run test
workflow:
  version: 2
  build:
    jobs:
      - build
