version: '2.1'
services:
    api:
        restart: always
        build:
            context: ../
            dockerfile: docker/Dockerfile
        volumes:
            - ../:/usr/src
        ports:
            - "3000:3000"
        depends_on:
            database:
                condition: service_healthy
        links:
            - database
        environment:
            NODE_ENV: development
            PORT: 3000
        env_file:
            - ../.env
    database:
        image: postgres:alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=doczy
            - POSTGRES_PASSWORD=doczy
            - POSTGRES_DB=doczy
        healthcheck:
            test: ["CMD-SHELL", "psql -h 'localhost' -U 'postgres' -c '\\l'"]
            interval: 30s
            timeout: 30s
            retries: 3
