export const LOGOUT = 'LOGOUT';
export const LOGIN = 'LOGIN';
export const CREATE_USER = 'CREATE_USER';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';


export const CLOSE_DOCUMENT = 'CLOSE_DOCUMENT';
export const CREATE_DOCUMENT = 'CREATE_DOCUMENT';
export const CREATION_SUCCESS = 'CREATION_SUCCESS';
export const CREATION_FAILURE = 'CREATION_FAILURE';

export const UPDATE_DOCUMENT = 'EDIT_DOCUMENT';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
export const UPDATE_FAILURE = 'UPDATE_FAILURE';

export const DELETE_DOCUMENT = 'DELETE_DOCUMENT';
export const DELETE_SUCCESS = 'DELETE_SUCCESS';
export const DELETE_FAILURE = 'DELETE_FAILURE';

export const GET_DOCUMENT = 'GET_DOCUMENT';
export const GET_SUCCESS = 'GET_SUCCESS';
export const GET_FAILURE = 'GET_FAILURE';

export const DOCUMENTS_RETRIEVAL = 'DOCUMENTS_RETRIEVAL';
export const DOCUMENTS_RETRIEVAL_SUCCESS = 'DOCUMENTS_RETRIEVAL_SUCCESS';
export const DOCUMENTS_RETRIEVAL_FAILURE = 'DOCUMENTS_RETRIEVAL_FAILURE';

export const SET_DOCUMENTS_SEARCH_FILTER = 'SET_DOCUMENTS_SEARCH_FILTER';
