export const LOGOUT = 'LOGOUT';
export const LOGIN = 'LOGIN';
export const CREATE_USER = 'CREATE_USER';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const SET_DOCUMENTS_SEARCH_FILTER = 'SET_DOCUMENTS_SEARCH_FILTER';

export const CLOSE_DOCUMENT = 'CLOSE_DOCUMENT';
export const DOCUMENT_REQUEST = 'DOCUMENT_REQUEST';
export const DOCUMENT_SUCCESS = 'DOCUMENT_SUCCESS';
export const DOCUMENT_FAILURE = 'DOCUMENT_FAILURE';

export const DOCUMENT_ADD_REQUEST = 'DOCUMENT_ADD_REQUEST';
export const DOCUMENT_ADD_SUCCESS = 'DOCUMENT_ADD_SUCCESS';
export const DOCUMENT_ADD_FAILURE = 'DOCUMENT_ADD_FAILURE';

export const DOCUMENT_GET_REQUEST = 'DOCUMENT_GET_REQUEST';
export const DOCUMENT_GET_SUCCESS = 'DOCUMENT_GET_SUCCESS';
export const DOCUMENT_GET_FAILURE = 'DOCUMENT_GET_FAILURE';

export const DOCUMENT_UPDATE_REQUEST = 'DOCUMENT_UPDATE_REQUEST';
export const DOCUMENT_UPDATE_SUCCESS = 'DOCUMENT_UPDATE_SUCCESS';
export const DOCUMENT_UPDATE_FAILURE = 'DOCUMENT_UPDATE_FAILURE';

export const DOCUMENT_DELETE_REQUEST = 'DOCUMENT_DELETE_REQUEST';
export const DOCUMENT_DELETE_SUCCESS = 'DOCUMENT_DELETE_SUCCESS';
export const DOCUMENT_DELETE_FAILURE = 'DOCUMENT_DELETE_FAILURE';


export const APP_LOAD = 'APP_LOAD';
export const REDIRECT = 'REDIRECT';

export const ROLE_REQUEST = 'ROLE_REQUEST';
export const ROLE_SUCCESS = 'ROLE_SUCCESS';
export const ROLE_FAILURE = 'ROLE_FAILURE';

export const ROLE_ADD_REQUEST = 'ROLE_ADD_REQUEST';
export const ROLE_ADD_SUCCESS = 'ROLE_ADD_SUCCESS';
export const ROLE_ADD_FAILURE = 'ROLE_ADD_FAILURE';

export const ROLE_DELETE_REQUEST = 'ROLE_DELETE_REQUEST';
export const ROLE_DELETE_SUCCESS = 'ROLE_DELETE_SUCCESS';
export const ROLE_DELETE_FAILURE = 'ROLE_DELETE_FAILURE';

export const ROLE_UPDATE_REQUEST = 'ROLE_UPDATE_REQUEST';
export const ROLE_UPDATE_SUCCESS = 'ROLE_UPDATE_SUCCESS';
export const ROLE_UPDATE_FAILURE = 'ROLE_UPDATE_FAILURE';



